version: '3.8'

services: 
  postgres:
    image: postgres:15
    container_name: de_postgres
    environment:
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: uadmlt123
      POSTGRES_DB: data_engineering
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:



# version: '3.8'

# services: 
#   postgres:
#     image: postgres:15
#     container_name: dw_postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: dw
#     ports:
#       - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data

# volumes:
#   pg_data: